[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_TMDB_API_KEY = "18f5b196262c331e2e29bcbe652ffdba"
  VITE_FIREBASE_API_KEY = "AIzaSyBZCTx_eQEZ5_AmpJYXk6FYyLJoIFpTjkc"
  VITE_FIREBASE_AUTH_DOMAIN = "kalstream-b2daf.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "kalstream-b2daf"
  VITE_FIREBASE_STORAGE_BUCKET = "kalstream-b2daf.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "395137029438"
  VITE_FIREBASE_APP_ID = "1:395137029438:web:2b42f26b59f4e22ff91202"
  VITE_FIREBASE_MEASUREMENT_ID = "G-XC71BF1WP9"